-- 1. ADD ADMIN USER SUPPORT
ALTER TABLE Users ADD COLUMN IF NOT EXISTS email VARCHAR(255) UNIQUE;
ALTER TABLE Users ADD COLUMN IF NOT EXISTS is_admin BOOLEAN DEFAULT false;
ALTER TABLE Users ADD COLUMN IF NOT EXISTS password VARCHAR(255);

-- 2. CREATE SETTINGS TABLE FOR TIMER
CREATE TABLE IF NOT EXISTS Settings (
    key VARCHAR(50) PRIMARY KEY,
    value TEXT NOT NULL
);

-- 3. INSERT DEFAULT TIMER
INSERT INTO Settings (key, value) VALUES ('CONTEST_START', '2026-03-10T00:00:00+05:30') ON CONFLICT (key) DO UPDATE SET value = '2026-03-10T00:00:00+05:30';
INSERT INTO Settings (key, value) VALUES ('CONTEST_END', '2026-03-20T00:00:00+05:30') ON CONFLICT (key) DO UPDATE SET value = '2026-03-20T00:00:00+05:30';

-- 4. INSERT ADMIN CREDENTIALS AS REQUESTED
INSERT INTO Users (name, email, is_admin, password) 
VALUES ('Harsh', 'admin@error.com', true, 'error@gfg')
ON CONFLICT (email) DO UPDATE SET is_admin = true, password = 'error@gfg';
